export const UZBEKISTAN_LOCATIONS: Record<string, string[]> = {
  "Toshkent shahri": [
    "Bektemir tumani",
    "Chilonzor tumani",
    "Yashnobod tumani",
    "Mirobod tumani",
    "Mirzo Ulugʻbek tumani",
    "Sergeli tumani",
    "Shayxontohur tumani",
    "Olmazor tumani",
    "Uchtepa tumani",
    "Yakkasaroy tumani",
    "Yunusobod tumani",
    "Yangihayot tumani"
  ],
  "Xorazm viloyati": [
    "Bogʻot tumani",
    "Gurlan tumani",
    "Xonqa tumani",
    "Hazorasp tumani",
    "Xiva tumani",
    "Qoʻshkoʻpir tumani",
    "Shovot tumani",
    "Urganch tumani",
    "Yangiariq tumani",
    "Yangibozor tumani",
    "Tuproqqalʼa tumani",
    "Xiva shahri",
    "Urganch shahri"
  ],
  "Qoraqalpogʻiston": [
    "Amudaryo tumani",
    "Beruniy tumani",
    "Chimboy tumani",
    "Ellikqalʼa tumani",
    "Kegeyli tumani",
    "Moʻynoq tumani",
    "Nukus tumani",
    "Qanlikoʻl tumani",
    "Qoʻngʻirot tumani",
    "Qoraoʻzak tumani",
    "Shumanay tumani",
    "Taxtakoʻpir tumani",
    "Toʻrtkoʻl tumani",
    "Xoʻjayli tumani",
    "Taxiatosh tumani",
    "Boʻzatov tumani"
  ],
  "Andijon viloyati": [
    "Andijon tumani",
    "Asaka tumani",
    "Baliqchi tumani",
    "Bo'ston tumani",
    "Buloqboshi tumani",
    "Izboskan tumani",
    "Jalaquduq tumani",
    "Xoʻjaobod tumani",
    "Qoʻrgʻontepa tumani",
    "Marhamat tumani",
    "Oltinkoʻl tumani",
    "Paxtaobod tumani",
    "Shahrixon tumani",
    "Ulugʻnor tumani"
  ],
  "Fargʻona viloyati": [
    "Oltiariq tumani",
    "Bagʻdod tumani",
    "Beshariq tumani",
    "Buvayda tumani",
    "Dangʻara tumani",
    "Fargʻona tumani",
    "Furqat tumani",
    "Qoʻshtepa tumani",
    "Quva tumani",
    "Rishton tumani",
    "Soʻx tumani",
    "Toshloq tumani",
    "Uchkoʻprik tumani",
    "Oʻzbekiston tumani",
    "Yozyovon tumani"
  ],
  "Namangan viloyati": [
    "Chortoq tumani",
    "Chust tumani",
    "Kosonsoy tumani",
    "Mingbuloq tumani",
    "Namangan tumani",
    "Norin tumani",
    "Pop tumani",
    "Toʻraqoʻrgʻon tumani",
    "Uchqoʻrgʻon tumani",
    "Uychi tumani",
    "Yangiqoʻrgʻon tumani"
  ],
  "Toshkent viloyati": [
    "Bekobod tumani",
    "Boʻstonliq tumani",
    "Boʻka tumani",
    "Chinoz tumani",
    "Qibray tumani",
    "Ohangaron tumani",
    "Oqqoʻrgʻon tumani",
    "Parkent tumani",
    "Piskent tumani",
    "Quyi Chirchiq tumani",
    "Oʻrta Chirchiq tumani",
    "Yangiyoʻl tumani",
    "Yuqori Chirchiq tumani",
    "Zangiota tumani"
  ],
  "Sirdaryo viloyati": [
    "Oqoltin tumani",
    "Boyovut tumani",
    "Guliston tumani",
    "Xovos tumani",
    "Mirzaobod tumani",
    "Sayxunobod tumani",
    "Sardoba tumani",
    "Sirdaryo tumani"
  ],
  "Jizzax viloyati": [
    "Arnasoy tumani",
    "Baxmal tumani",
    "Doʻstlik tumani",
    "Forish tumani",
    "Gʻallaorol tumani",
    "Sharof Rashidov tumani",
    "Mirzachoʻl tumani",
    "Paxtakor tumani",
    "Yangiobod tumani",
    "Zomin tumani",
    "Zafarobod tumani",
    "Zarbdor tumani"
  ],
  "Surxondaryo viloyati": [
    "Angor tumani",
    "Boysun tumani",
    "Denov tumani",
    "Jarqoʻrgʻon tumani",
    "Qiziriq tumani",
    "Qumqoʻrgʻon tumani",
    "Muzrabot tumani",
    "Oltinsoy tumani",
    "Sariosiyo tumani",
    "Sherobod tumani",
    "Shoʻrchi tumani",
    "Termiz tumani",
    "Uzun tumani",
    "Bandixon tumani"
  ],
  "Qashqadaryo viloyati": [
    "Chiroqchi tumani",
    "Dehqonobod tumani",
    "Gʻuzor tumani",
    "Qamashi tumani",
    "Qarshi tumani",
    "Koson tumani",
    "Kasbi tumani",
    "Kitob tumani",
    "Mirishkor tumani",
    "Muborak tumani",
    "Nishon tumani",
    "Shahrisabz tumani",
    "Yakkabogʻ tumani",
    "Koʻkdala tumani"
  ],
  "Samarqand viloyati": [
    "Bulungʻur tumani",
    "Ishtixon tumani",
    "Jomboy tumani",
    "Kattaqoʻrgʻon tumani",
    "Qoʻshrabot tumani",
    "Narpay tumani",
    "Nurobod tumani",
    "Oqdaryo tumani",
    "Paxtachi tumani",
    "Payariq tumani",
    "Pastdargʻom tumani",
    "Samarqand tumani",
    "Toyloq tumani",
    "Urgut tumani"
  ],
  "Buxoro viloyati": [
    "Olot tumani",
    "Buxoro tumani",
    "Gʻijduvon tumani",
    "Jondor tumani",
    "Kogon tumani",
    "Qorakoʻl tumani",
    "Qorovulbozor tumani",
    "Peshku tumani",
    "Romitan tumani",
    "Shofirkon tumani",
    "Vobkent tumani"
  ],
  "Navoiy viloyati": [
    "Konimex tumani",
    "Karmana tumani",
    "Qiziltepa tumani",
    "Xatirchi tumani",
    "Navbahor tumani",
    "Nurota tumani",
    "Tomdi tumani",
    "Uchquduq tumani"
  ]
};
